name: diagnosify
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.69.0
  lottie: ^3.1.2
  flutter_staggered_animations: ^1.1.1
  flutter_animate: ^4.5.0
  permission_handler: ^10.2.0
  image_picker: ^1.1.2
  flutter_launcher_icons: ^0.14.1
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  firebase_storage: ^12.3.4
  cloud_firestore: ^5.4.4
  intl_phone_field: ^3.2.0
  tflite_flutter: ^0.11.0
  image: ^4.0.15
  pdf: ^3.11.1
  printing:
  intl:
  camera:

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/app_icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
