name: diagnosify
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.69.0
  lottie: ^2.3.2
  flutter_staggered_animations: ^1.1.1
  flutter_animate: ^4.5.0
  permission_handler: ^10.2.0
  image_picker: ^1.1.2
  flutter_launcher_icons: ^0.14.1
flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/app_icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  

flutter:
  uses-material-design: true
  
  assets:
    - assets/
