// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWoZaIybOJYaQxt5rJBllD7m3BTAyj9tk',
    appId: '1:499940209322:web:f8fcf6d10b58f73fc396d3',
    messagingSenderId: '499940209322',
    projectId: 'diagnosify-c400e',
    authDomain: 'diagnosify-c400e.firebaseapp.com',
    storageBucket: 'diagnosify-c400e.appspot.com',
    measurementId: 'G-SEC7DCPWPW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXkfm-770GjgDE5zXEWH-a8MF6_ma3l0Y',
    appId: '1:499940209322:android:4ec7e9cc45049c59c396d3',
    messagingSenderId: '499940209322',
    projectId: 'diagnosify-c400e',
    storageBucket: 'diagnosify-c400e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXGbhVKZXhuikV4I30Azls4UuIiqbL6Xc',
    appId: '1:499940209322:ios:d941b1817c82cb6dc396d3',
    messagingSenderId: '499940209322',
    projectId: 'diagnosify-c400e',
    storageBucket: 'diagnosify-c400e.appspot.com',
    iosBundleId: 'com.example.diagnosify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXGbhVKZXhuikV4I30Azls4UuIiqbL6Xc',
    appId: '1:499940209322:ios:d941b1817c82cb6dc396d3',
    messagingSenderId: '499940209322',
    projectId: 'diagnosify-c400e',
    storageBucket: 'diagnosify-c400e.appspot.com',
    iosBundleId: 'com.example.diagnosify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWoZaIybOJYaQxt5rJBllD7m3BTAyj9tk',
    appId: '1:499940209322:web:566980db30431425c396d3',
    messagingSenderId: '499940209322',
    projectId: 'diagnosify-c400e',
    authDomain: 'diagnosify-c400e.firebaseapp.com',
    storageBucket: 'diagnosify-c400e.appspot.com',
    measurementId: 'G-BNQXDG9PNE',
  );
}
